require("busted")
require("latex-twitter")

describe("Encoding of URLs", function()
    it("encodes hashtags", function()
        assert.same("%23", urlencode("#"))
    end)
    it("encodes spaces", function()
        assert.same("%20", urlencode(" "))
    end)
    it("encodes questionmarks", function()
        assert.same("%3F", urlencode("?"))
    end)
    it("encodes ampersands", function()
        assert.same("%26", urlencode("&"))
    end)
    it("encodes letters", function()
        assert.same("a", urlencode("a"))
    end)
end)