require("busted")
require("latex-twitter")

describe("Encoding of URLs", function()
    it("should encode hashtags", function()
        assert.same("%23", urlencode("#"))
    end)
    it("should encode spaces", function()
        assert.same("%20", urlencode(" "))
    end)
    it("should encode questionmarks", function()
        assert.same("%3F", urlencode("?"))
    end)
    it("should encode ampersands", function()
        assert.same("%26", urlencode("&"))
    end)
    it("should encode letters", function()
        assert.same("a", urlencode("a"))
    end)
    it("should encodes URLs", function ()
        assert.same("http%3A%2F%2Fwww%2Eexample%2Ecom%2Findex%2Ephp%3Fid%3D123%26name%3DTest", urlencode("http://www.example.com/index.php?id=123&name=Test"))
    end)
end)